// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SounDojo
{
	public partial class OptionsViewController : UIViewController
	{
		public OptionsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
