// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using SounDojo;

namespace iPhone
{
	public partial class PlaylistViewController : UIViewController
	{
		Playlist playlist;

		public PlaylistViewController (IntPtr handle) : base (handle)
		{
		}

		#region View lifecycle

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			playlistView.Source = playlist;
			if (playlist.CurrentSongIndex < playlist.TracksCount)
				playlistView.SelectRow (NSIndexPath.FromRowSection (playlist.CurrentSongIndex, 0), true, UITableViewScrollPosition.Middle);
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
		}

		public override void ViewWillDisappear (bool animated)
		{
			base.ViewWillDisappear (animated);
		}

		public override void ViewDidDisappear (bool animated)
		{
			base.ViewDidDisappear (animated);
		}

		#endregion

		partial void back (UIBarButtonItem sender)
		{
			this.DismissViewController (true,null);

			if (Back != null)
				Back (this, EventArgs.Empty);
		}

		public event EventHandler Back;

		public void SetPlaylistSource(Playlist playlist) {
			this.playlist = playlist;
		}
	}
}
